name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - qa

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          echo '{"result":"All tests passed ✅"}' > test-report.json

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-report.json

      - name: Build project
        run: |
          mkdir -p build
          echo "Sample build file" > build/index.html

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build/

  deploy_qa:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/qa'
    steps:
      - name: Download test report
        uses: actions/download-artifact@v4
        with:
          name: test-report
          path: ./artifacts/test

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./artifacts/build

      - name: Deploy to QA
        run: |
          echo "🚀 Deploying to QA environment"
          echo "📋 Test Report:"
          cat artifacts/test/test-report.json
          echo "📦 Build Artifact contents:"
          ls -R artifacts/build

  deploy_prod:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download test report
        uses: actions/download-artifact@v4
        with:
          name: test-report
          path: ./artifacts/test

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./artifacts/build

      - name: Deploy to Production
        run: |
          echo "🚀 Deploying to PRODUCTION environment"
          echo "📋 Test Report:"
          cat artifacts/test/test-report.json
          echo "📦 Build Artifact contents:"
          ls -R artifacts/build
